### ISSUE TITLE
Empty appearance DEF names

### ISSUE THREAD

**Issue by Marius-Juston** [cyberbotics/blender-webots-exporter#5]
I was trying to export the blender file below and it did not give me any problems then but when I tried opening it in Webots it gave me:
`ERROR: 'C:/Users/***/Documents/Inventor/FRC Field 2019/FRC Field 2019.wbt':17:37: error: Expected node or PROTO name, found '{'.`
`ERROR: 'C:/Users/***/Documents/Inventor/FRC Field 2019/FRC Field 2019.wbt': Failed to load due to syntax error(s).`

I am in Webots R2019b and in Windows 10

https://drive.google.com/open?id=1kuIG4Jh2BoMZ4Qza5nOWXdTzLzb_mli0

**Comment by DavidMansolino** [comment]
I can reproduce the problem, thîs is due to an issue when defining the appearances DEF names, which are in some cases empty:
```
appearance DEF  PBRAppearance {
```

We will fix the importer to avoid such cases, in the meantime you can simply do a search and replace in your *.wbt file (replace `appearance DEF  PBRAppearance {` by `appearance PBRAppearance {`), I just tried and it seems to work fine:
![FRC Field 2019](https://user-images.githubusercontent.com/2461619/62932408-593c3800-bdc0-11e9-87c4-a3be68f7c983.png)

Be aware the number of triangles of your model is very high, I strongly recommend reducing the number of triangles of some key part of your model to keep a simulation speed and memory usage reasonable in Webots.

**Comment by Marius-Juston** [comment]
Thanks it seems that it works now!

**Comment by DavidMansolino** [comment]
Perfect, thank you for the feedback.
Just for information, the fix is ready here: https://github.com/omichel/blender-webots-exporter/pull/6
